In [37]:
predictions = [[0, 1, 0], [0, 1, 1], [0, 0, 0], [0, 0, 1]]

In [38]:
samples = len(predictions[0])
samples

3

In [40]:
for i in range(samples):
    print(f"Vị trí {i}:")
    for pred in predictions:
        print(pred[i])

Vị trí 0:
0
0
0
0
Vị trí 1:
1
1
0
0
Vị trí 2:
0
1
0
1


In [25]:
pos = 0

for i, pred in enumerate(predictions):
    print(pred[0])

0
0
0
0


In [31]:
pos = 0 
for pred in predictions:
    if pos < samples:
        print(pred[0])
        pos += 1
    else:
        break

0
0
0


In [ ]:
key: số 
value: freq

In [ ]:



result = random_forest_vote(predictions)
result

[0, 0, 0]

In [50]:
store = [1,1,0]

In [51]:
fred = {}
for val in store:
    if val not in fred.values():
        fred[val] = 0
    fred[val] += 1
highest = max(fred)


In [52]:

highest

1

In [15]:
import math

def rotate_image(image, angle_degrees):
    """
    Rotate the image counterclockwise by the given angle using nearest neighbor interpolation.
    """
    # Write code here
    H = len(image)
    W = len(image[0])

    # Center of the image
    cy = (H-1)/2
    cx = (W-1)/2

    output = [[0 for _ in range(W)] for _ in range(H)]
    for i in range(H):
        for j in range(W):
            dy = i - cy 
            dx = j - cx
            src_y = cy + dy*math.cos(angle_degrees) + dx*math.sin(angle_degrees)
            src_x = cx + dy*math.sin(angle_degrees) + dx*math.cos(angle_degrees)
            src_y = int(round(src_y))
            src_x = int(round(src_x))
            if src_x <= W and src_y <= H:
                output[i][j] = image[src_x][src_y]
    return output


image = [[1,2,3],[4,5,6],[7,8,9]]
angle_degrees = 0

In [16]:
output = rotate_image(image, angle_degrees)
output

[[1, 4, 7], [2, 5, 8], [3, 6, 9]]

In [17]:
C=[[10,20],[20,10]]

In [18]:
r, c = len(C), len(C[0])

In [26]:
import math 
def bilinear_resize(image, new_h, new_w):
    """
    Resize a 2D grid using bilinear interpolation.
    """
    # Write code here
    height = len(image)
    width = len(image[0])
    output = [[0.0 for _ in range(height)] for _ in range(width)]
    for i in range(height):
        for j in range(width): 
            src_y = i * ((height-1)/(new_h-1))
            src_x = j * ((width-1)/(new_w-1))

            y_0 = math.floor(src_y)
            x_0 = math.floor(src_x)

            dy = src_y - y_0
            dx = src_x - x_0

            y_1 = min(y_0 + 1, height - 1)
            x_1 = min(x_0 + 1, width - 1)

            result = image[y_0][x_0]*(1-dy)(1-dx) + image[y_1][x_0]*dy*(1-dx) + image[y_0][x_1] * (1-dy)*dx + image[y_1][x_1]*dy*dx

            output[i][j] = result
    return output 
            
image = [[0, 10], [20, 30]] 
new_h = 3
new_w = 3

In [27]:
bilinear_resize(image, new_h, new_w)

TypeError: 'float' object is not callable

In [23]:
math.floor(2.7)

2

In [25]:
dy = 2.7 - 2
dy

0.7000000000000002

In [ ]:
x=[2., 4.]
p=0.5 

In [30]:
import numpy as np 
def dropout(x, p=0.5, rng=None):
    """
    Apply dropout to input x with probability p.
    Return (output, dropout_pattern).
    """
    # Write code here
    n = len(x)
    d = len(x[0])
    x = np.random.random((n,d))
     
    non_p = 1 - p

In [35]:
x=[2., 4.]
n = len(x)
p= 0.2
output = np.random.random(n)

In [36]:
output

array([0.73119089, 0.75665409])

In [37]:
output[output >= p] = 0

In [38]:
output

array([0., 0.])

In [2]:
from collections import Counter

counter = Counter(["dog", "cat", "dog", "dog", "cat"])

most_common_item = counter.most_common(1)

In [6]:
most_common_item[0][0]

'dog'

In [1]:
production_log = [   {"input_id": 1, "prediction": 1, "actual": 1, "latency_ms": 15},   {"input_id": 2, "prediction": 0, "actual": 1, "latency_ms": 20},   {"input_id": 3, "prediction": 1, "actual": 1, "latency_ms": 18},   {"input_id": 4, "prediction": 0, "actual": 0, "latency_ms": 22}, ] 
shadow_log = [   {"input_id": 1, "prediction": 1, "actual": 1, "latency_ms": 10},   {"input_id": 2, "prediction": 1, "actual": 1, "latency_ms": 25},   {"input_id": 3, "prediction": 1, "actual": 1, "latency_ms": 20},   {"input_id": 4, "prediction": 0, "actual": 0, "latency_ms": 30}, ] 
criteria = {"min_accuracy_gain": 0.0, "max_latency_p95": 50.0, "min_agreement_rate": 0.5}

In [7]:
production_log[0]['prediction']

1

In [8]:
x=[1,2,3,4]
q=[25,50,75]

In [ ]:
import numpy as np
import math
def percentiles(x, q):
    """
    Compute percentiles using linear interpolation.
    """
    result = []
    x_sorted = sorted(x)
    n_data = len(x_sorted)
    n_pen = len(q) 
    for i in range(n_pen):
        L = q[i]/100 * (n_data+1)
        if L.is_integer():
            result.append(x_sorted[int(L)])
            print(x_sorted[int(L)])
        else:
            x_1 = int(math.floor(L))
            x_2 = x_1 + 1 
            percent = x_sorted[x_1-1] + 0.5 * (x_sorted[x_2-1] - x_sorted[x_1-1])
            result.append(percent)
    return np.array(result)
x=[1,2,3,4]
q=[15, 20, 25, 40, 50]
percentiles(x, q)

array([1.5, 2.5, 3.5])

In [2]:
import numpy as np

def adamw_step(w, m, v, grad, lr=0.001, beta1=0.9, beta2=0.999, weight_decay=0.01, eps=1e-8):
    """
    Perform one AdamW update step.
    """
    # Write code here
    m_t = beta1*m + (1-beta1)*grad
    v_t = beta2*v + (1-beta2)*grad**2
    w = w - lr*(weight_decay*w) - lr*(m/(np.sqrt(v)+eps))
    return m_t, v_t, w
w = [1.0, -2.0]
m = [0.0, 0.0]
v = [0.0, 0.0]
grad = [0.3, -0.7]
lr=0.01
weight_decay=0
adamw_step(w, m, v, grad, lr=0.01, weight_decay=0)

TypeError: can't multiply sequence by non-int of type 'float'